<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PS8586" name="com.emotion.tests.CaptionTypeTests" tests="6" failures="0" timestamp="7 Dec 2015 17:49:00 GMT" time="149.527" errors="1">
  <testcase name="editCaptionTypeView" time="48.743" classname="com.emotion.tests.CaptionTypeTests"/>
  <testcase name="deleteCaptionType" time="3.903" classname="com.emotion.tests.CaptionTypeTests"/>
  <testcase name="metadataCaptionType" time="50.560" classname="com.emotion.tests.CaptionTypeTests"/>
  <testcase name="verifyCreateCaptiontype" time="27.193" classname="com.emotion.tests.CaptionTypeTests">
    <error type="java.lang.AssertionError" message="FAILED | TEST ID : 1 | Create caption type-puneTeam Message displayed was: The name puneTeam is already in use. Please select another.">
      <![CDATA[java.lang.AssertionError: FAILED | TEST ID : 1 | Create caption type-puneTeam Message displayed was: The name puneTeam is already in use. Please select another.
	at org.testng.Assert.fail(Assert.java:94)
	at com.emotion.core.TestStatus.fail(TestStatus.java:27)
	at com.emotion.tests.CaptionTypeTests.verifyCreateCaptiontype(CaptionTypeTests.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- verifyCreateCaptiontype -->
  <testcase name="cloneCaptionType" time="9.336" classname="com.emotion.tests.CaptionTypeTests"/>
  <testcase name="verifyCreateCaptiontype" time="9.792" classname="com.emotion.tests.CaptionTypeTests"/>
</testsuite> <!-- com.emotion.tests.CaptionTypeTests -->
